### Tensor 변환
- torch.as.tendor : 동일 타입과 디바이스를 가진 데이터 존재 ==> view, 즉 테이터 공유
- 다른 타입 또는 다른 디바이스를 가진 데이터 존재 => copy(), 즉 영상 생성
* view tensor 또는 copytensor 반환

In [19]:
import torch

- Python 객체 ==> Tensor 변환

In [20]:
## List ==> Tensor
data = list(range(1,10))

In [21]:
## torch.as_tensor()
dataTS = torch.as_tensor(data, dtype=torch.int8)
dataTS, dataTS.shape, dataTS.ndim, dataTS.dtype

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int8),
 torch.Size([9]),
 1,
 torch.int8)

In [22]:
data[0] = 100
data, dataTS

([100, 2, 3, 4, 5, 6, 7, 8, 9],
 tensor([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int8))

- Numpy ndarray 객체 ==> Tensor 변환

In [23]:
import numpy as np

In [24]:
arr1 = np.array([1,2,3])
arr1

array([1, 2, 3])

In [25]:
arrTS = torch.as_tensor(arr1)
arrTS

tensor([1, 2, 3], dtype=torch.int32)

In [26]:
arr1[0] = 77

In [27]:
arrTS[0] = 99

In [28]:
arr1, arrTS

(array([99,  2,  3]), tensor([99,  2,  3], dtype=torch.int32))

In [29]:
# 디바이스를 따로 설정 안하면 메모리 공유 => view 방식 <-> 복사본 : copy()
# sharing 일지 copy일지 알 수 없음

- Numpy ndarray ==> Tensor 변환 : from_numpy()

In [30]:
arr1 = np.array([[5,7,9], [1,2,3,]], dtype=np.float32)
print(arr1)
print(f'데이터 저장 메모리 : {arr1.data}')
print(f'원소/요소 개수 : {arr1.size}')
print(f'원소/요소 1개 크기 : {arr1.itemsize}')
print(f'타입 : {arr1.dtype}')
print(f'방향 : {arr1.strides}')

[[5. 7. 9.]
 [1. 2. 3.]]
데이터 저장 메모리 : <memory at 0x00000284ECF37AD0>
원소/요소 개수 : 6
원소/요소 1개 크기 : 4
타입 : float32
방향 : (12, 4)


In [31]:
arrTS = torch.from_numpy(arr1)
arrTS

tensor([[5., 7., 9.],
        [1., 2., 3.]])