### Tensor 모양/형태/shape변경과 View Tensor

In [1]:
### 모듈 로딩
import torch
import numpy as pd

In [14]:
## 첸서 생성
dataTS = torch.arange(1,21)
print(dataTS, dataTS.ndim, dataTS.stride(),sep='\n')
print(f'is_contiguous() : {dataTS.is_contiguous()}')

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
        19, 20])
1
(1,)
is_contiguous() : True


In [13]:
# 1D => 2D 형태/모양/shape 변경
dataTS2 = dataTS.reshape((-1,5))
print(dataTS2, dataTS2.ndim, dataTS2.stride(),sep='\n')
print(f'is_contiguous() : {dataTS2.is_contiguous()}')

tensor([[77,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]])
2
(5, 1)
is_contiguous() : True


In [7]:
print(dataTS2.storage())

 1
 2
 3
 4
 5
 6
 7
 8
 9
 10
 11
 12
 13
 14
 15
 16
 17
 18
 19
 20
[torch.storage.TypedStorage(dtype=torch.int64, device=cpu) of size 20]


C:\Users\kdp\AppData\Local\Temp\ipykernel_13960\104493862.py:1: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  print(dataTS2.storage())


In [8]:
print(dataTS.storage())

 1
 2
 3
 4
 5
 6
 7
 8
 9
 10
 11
 12
 13
 14
 15
 16
 17
 18
 19
 20
[torch.storage.TypedStorage(dtype=torch.int64, device=cpu) of size 20]


In [10]:
dataTS2[0][0] = 77

In [11]:
dataTS, dataTS2
# 둘다 바뀜 => view 텐서 반환

(tensor([77,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
         19, 20]),
 tensor([[77,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10],
         [11, 12, 13, 14, 15],
         [16, 17, 18, 19, 20]]))

In [15]:
dataTS22 = dataTS2.reshape((-1,2))
print(dataTS22, dataTS22.ndim, dataTS22.stride(),sep='\n')
print(f'is_contiguous() : {dataTS22.is_contiguous()}')

tensor([[77,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10],
        [11, 12],
        [13, 14],
        [15, 16],
        [17, 18],
        [19, 20]])
2
(2, 1)
is_contiguous() : True


In [17]:
dataTS23 = dataTS22.T
dataTS23.is_contiguous()

False

In [19]:
## 불연속적인 텐서 ==> 연속적으로 저장되도록
dTS = dataTS23.contiguous()
dTS.storage()

 77
 3
 5
 7
 9
 11
 13
 15
 17
 19
 2
 4
 6
 8
 10
 12
 14
 16
 18
 20
[torch.storage.TypedStorage(dtype=torch.int64, device=cpu) of size 20]

In [20]:
dataTS.storage()

 1
 2
 3
 4
 5
 6
 7
 8
 9
 10
 11
 12
 13
 14
 15
 16
 17
 18
 19
 20
[torch.storage.TypedStorage(dtype=torch.int64, device=cpu) of size 20]