In [1]:
import numpy as np

#### 내부 조작 함수

In [2]:
# 정렬함수 sort()
a = np.linspace(1,6,6, dtype=np.int32)
np.random.shuffle(a)
a

array([2, 4, 6, 1, 3, 5])

In [4]:
a.sort()
a

array([1, 2, 3, 4, 5, 6])

In [5]:
# 정렬함수 argsort() : 값이 아닌 인덱스를 정렬
#                     기존 원본 배열의 인덱스를 가지고 정렬한 배열 반환
np.random.shuffle(a)
a

array([2, 6, 3, 5, 4, 1])

In [6]:
b = np.argsort(a)
b

array([5, 0, 2, 4, 3, 1], dtype=int64)

In [7]:
a[b[0]]

1

In [8]:
a[b[3]]

4

In [9]:
# 배열 클래스 변경 : ndarray(다차원배열)와 matrix(행렬처리)클래스는 서로 자료형 교환 가능
m = np.matrix([1,2,3,4])
m

matrix([[1, 2, 3, 4]])

In [10]:
type(m)

numpy.matrix

In [11]:
# 자료형 변경
a = np.asarray(m)
a

array([[1, 2, 3, 4]])

In [12]:
type(a)

numpy.ndarray

In [13]:
m1 = np.asmatrix(a)
m1

matrix([[1, 2, 3, 4]])

In [14]:
# 배열의 값 변경 : 모든 원소를 다른 값으로 변경 => fill() 사용
#                 새로 만드는 배열의 모든 값을 동일하게 처리 => full()

In [15]:
# 위치 변경 및 이동 : 배열의 좌우, 상하의 위치 및 각도에 따라 이동 가능
# np.fliplr() / flipud() : 배열의 좌우, 상하 이동
array = np.arange(4).reshape((2,2))
array

array([[0, 1],
       [2, 3]])

In [16]:
np.fliplr(array)

array([[1, 0],
       [3, 2]])

In [17]:
np.flipud(array)

array([[2, 3],
       [0, 1]])

In [18]:
# np.rot90(배열을 반시계방향으로 90도 돌리기)
m = np.array([[1,2],[3,4]], int)
m

array([[1, 2],
       [3, 4]])

In [19]:
np.rot90(m,3)

array([[3, 1],
       [4, 2]])

In [20]:
# 배열 내의 원소 점검하기 : 원소의 값에 대한 체크 가능 / 무한대나 nan 점검 가능함
#                         isreal() / isinf() / isnan()
m = np.random.randn(3,5)
m

array([[ 1.06837278,  0.46753909,  1.38526964, -0.48111892,  0.81514489],
       [-0.21797111, -1.3226994 ,  1.44590624, -1.59262887,  0.45794974],
       [-0.64625012, -1.2343268 ,  0.46674775, -0.6425863 ,  0.2908368 ]])

#### 배열의 padding 처리

In [21]:
# 패딩 : 기존 배열 밖에 다른 원소를 더 붙여서 배열을 확장
x = np.arange(1,5).reshape(2,2)
x

array([[1, 2],
       [3, 4]])

In [22]:
# 패딩함수 : 함수 pad를 가지고 배열에 패딩 처리
# 상수값으로 패딩 : constant / 기존 배열의 값으로 패딩 : edge
# 패딩되는 값 최대, 최소, 평균, 중앙값 등으로 지정 가능
np.pad(x,(3,3),'median')

array([[2, 2, 2, 2, 3, 2, 2, 2],
       [2, 2, 2, 2, 3, 2, 2, 2],
       [2, 2, 2, 2, 3, 2, 2, 2],
       [2, 2, 2, 1, 2, 2, 2, 2],
       [4, 4, 4, 3, 4, 4, 4, 4],
       [2, 2, 2, 2, 3, 2, 2, 2],
       [2, 2, 2, 2, 3, 2, 2, 2],
       [2, 2, 2, 2, 3, 2, 2, 2]])

In [24]:
np.pad(x,(1,0),'constant')

array([[0, 0, 0],
       [0, 1, 2],
       [0, 3, 4]])

In [25]:
np.pad(x,(0,1),'edge')

array([[1, 2, 2],
       [3, 4, 4],
       [3, 4, 4]])

## 넘파이 모듈의 자료형 이해하기

#### dtype으로 자료형 객체 생성하기

In [26]:
# dtype 클래스 : 다차원 배열의 자료형을 관리하는 클래스 , 이 클래스로 객체를 만들어서 관리
#               배열을 생성할 때 자료형 클래스가 dtype인자에 전달됨

In [27]:
np.int_
np.int_.mro()

[numpy.int32,
 numpy.signedinteger,
 numpy.integer,
 numpy.number,
 numpy.generic,
 object]

In [28]:
# 날짜 자료형 : 날짜는 연도,월,일 등의 기준 만듦, 그 다음에 시간이 있으면 시,분,초 등을 넣음
#              리스트에 날짜를 넣고 배열로 변경 가능, 두 날짜간의 일자를 계산하는 뺄셈 有

In [29]:
# 문자 자료형 : 파이썬의 문자 자료형 - 유니코드, 바이트
# 다차원 배열의 원소가 문자열일 때 dtype = 'S' => 바이트 문자열로 처리(문자열 앞에 'b' 붙음)
#                               dtype = 'U', np_str_등으로 처리 => 일반적인 문자열로 처리

## 시각화와 수학 함수 알아보기

#### 활성화 함수를 그래프로 그려보기

In [30]:
# 항등함수 : 입력과 출력이 동일한 결과, 즉 입력하는 값을 그대로 출력하는 값으로 처리하는 함수

## 수학 함수 알아보기

#### 산술 함수

In [31]:
# 소수점 이하 처리
# 소수점 이하를 버림 : fix, trunc / 소수점 이하를 올림이나 버림 : ceil, floor
# 소수점 이하와 소수점 이상의 수도 올림과 내림 처리 : round, around

In [32]:
# 산술 연산 : 배열에 대한 사칙연산을 기호나 함수등으로 처리 / 나머지와 몫을 구하는 함수
#                     add, true_divide, floor_divide   /    mod, remainder, divmod

In [33]:
# 부호, 절댓값 : 부호표시, 양수음수 변환함수, 음수를 없애는 절댓값 함수 처리
#                 sign  / positive,negative / abs, absolute

In [34]:
# 제곱근, 제곱 : 제곱근과 제곱을 처리 (square, power, sqrt)

#### 논리 및 비교 연산

In [35]:
# 논리연산 : 두개의 다차원 배열의 논리연산은 하나의 논리값을 결정하지 못해 별도의 논리함수 사용
#           logical_and / logical_or / ^ / logical_xor / logical_not

In [36]:
# 비교 연산 : 비교연산도 다차원배열의 원소별로 평가되어 표시 / 비교연산 기호에 따른 함수 제공
# 부등호 (>, |, <) / 넘파이 - less, greater, equal, less_equl, greater_equal, not_equal

In [37]:
# 수열의 합 : sum(합), cumsum(누적합)
# 수열의 곱 : prod(곱), cumprod(누적곱: axis=0 or axis=1)

In [38]:
# 결측값 계산 : 결측값이 있는 경우에 합 또는 곱을 구하면 nan 값으로 처리 
#              결측값을 제외하고 계산하려면 nansum, nancumsun, nanprod, nancumprod 사용

#### 지수와 로그 함수 이해하기

In [39]:
# 자연 상수의 지수 : 자연상수 e를 기준으로 처리
# 지수 함수 : 자연상수 e를 기준으로 지수함수를 만들어서 배열의 값을 지수로 넣고 계산
#            np.exp(0)

In [40]:
# 로그 함수 : e상수를 밑으로 처리하는 로그함수에 넣고 지수를 구함 / 기본으로 실수를 계산
# allclose() : 동일한 값인지 확인
x = np.arange(10000,1000000,100000)
x

array([ 10000, 110000, 210000, 310000, 410000, 510000, 610000, 710000,
       810000, 910000])

In [41]:
np.log(x)

array([ 9.21034037, 11.60823564, 12.25486281, 12.64432758, 12.92391244,
       13.142166  , 13.32121424, 13.47302025, 13.60478953, 13.72119988])

In [42]:
np.exp(9.21034037)

9999.99998023818

In [43]:
np.allclose(np.exp(9.21034037),10000)

True

#### 집합 이해하기

In [44]:
# 유일한 원소 : unique /  포함관계 확인 : in1d(원소(리스트도 가능함), array)

In [45]:
# 합집합 : union1d() / 교집합 : intersect1d()
# 차집합 : setdiff1d() / 대칭차집합 : setxor1d() => 교집합의 여집합

#### 삼각함수 이해하기

In [46]:
# 넘파이 모듈에서는 각도보다 라디안을 기준으로 삼각함수 계산
# 삼각함수는 원을 기준으로 삼각비를 계산하지만 쌍곡선함수는 쌍곡선을 기준으로 처리함

## 확률, 통계 함수 알아보기

#### 통계 함수

In [47]:
# 최대값에서 최소값을 뺀 범위 : ptp()
# 특정 수가 어느 %내에 속하는지 확인 : percentile(배열, 숫자) => 원소값 출력

In [48]:
# 평균값 : mean(), average() / 중앙값 : median()
# 모분산 : var() / 모표준편차 : std(), sqrt(var())
# 표본분산 : var(배열, ddof = 1)
# 표본표준편차 : std(배열, ddof = 1) /  sqrt(var(배열, ddof = 1))

In [ ]:
# 상관계수 : 두 변수의 상관관계 표시
# 공분산 : 두개의 확률 변수의 분포가 결합된 확률 분포의 분산
#         방향성은 나타내지만 결합정도에 대한 정보로서는 유용하지 않음