#### 성능지표 - 분류
- 정확도 (Accuracy) : 전체 정답에서 맞춘 정답의 수
- 정밀도 (Precision) : 모델(예측) 기준 모델이 True라고 한것이 정답(실제)도 True인 것
- 재현율 (Recall) : 정답(실제) 기준 정답이 True라고 한것이 모델(예측)도 True인 것
- F1 Score : 정밀도와 재현율 2가지를 조합한 점수
- 오차행렬 (Confusion Matrix) : 정답과 예측값의 관계를 나타내는 표

[1] 모듈 로딩 및 데이터 준비

In [32]:
# 모듈 로딩
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score              # sklearn에서 제공하는 성능평가 관련 모듈

import pandas as pd
import numpy as np

In [33]:
# 데이터 로딩
digitBunch = load_digits(as_frame=True)

[2] 피처와 레이블 추출

In [34]:
# 0~9까지 이미지 데이터값
imgDF = digitBunch['data']

# 0~9까지 라벨
labelSR = digitBunch['target']
labelSR.unique()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
## => 이진분류를 위해서 7과 나머지 레이블 변경  (교재 149쪽에 다른 방법도 있음)
mask = (labelSR == 7)

labelSR[~mask] = 0
labelSR[mask] = 1

In [36]:
labelSR.value_counts()

target
0    1618
1     179
Name: count, dtype: int64

[3] 학습용 데이터셋 준비

In [37]:
X_train, X_test, y_train, y_test = train_test_split(imgDF, labelSR, stratify=labelSR, random_state=1)

In [38]:
print('[Train]',y_train.value_counts()/y_train.shape[0])
print('\n[Test]',y_test.value_counts()/y_test.shape[0])

[Train] target
0    0.90052
1    0.09948
Name: count, dtype: float64

[Test] target
0    0.9
1    0.1
Name: count, dtype: float64


[4] 클래스 정의

In [39]:
# 사용자 정의 클래스 DummyClass : 아무것도 하지 않는 클래스, 단순 테스트용
from sklearn.base import BaseEstimator

class MyClassifier(BaseEstimator):
    def fit(self,X,y) : pass

    def predict(self, X) : return np.zeros((len(X),1), dtype=bool)

[5] 학습

In [40]:
# 인스턴스 생성
model = MyClassifier()

# 학습
model.fit(X_train, y_train)

[6] 예측 및 성능 평가

In [42]:
pre_ = model.predict(X_train)
pre_

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

[6-1] 정확도 => 불균형 데이터의 경우 신뢰 불가

In [43]:
accuracy_score(y_train, pre_)

0.9005196733481812

- 오차행렬

In [44]:
from sklearn.metrics import confusion_matrix, classification_report

In [47]:
# 정답과 예측값 전달
(tn,fp,fn,tp) = confusion_matrix(y_train, pre_).reshape(-1)
print(tn,fp,fn,tp)

1213 0 134 0


In [48]:
confusion_matrix(y_train, pre_)

array([[1213,    0],
       [ 134,    0]], dtype=int64)

- 정밀도(Precision) : 모델(예측) 중심

In [49]:
from sklearn.metrics import precision_score
precision_score(y_train, pre_, zero_division = 0)

0.0

- 재현율 : 정답(실제)중심

In [50]:
from sklearn.metrics import recall_score

recall_score(y_train, pre_)

0.0

[6-2] 오차행렬

In [51]:
from sklearn.metrics import confusion_matrix, classification_report

In [52]:
y_test=[0,0,0,1,1,  1,0,0,0,1,  1,1,1,0,0,  0,0,0,0,0]  # 정답 (실제)
y_pre=[1,1,1,1,1,  1,0,1,0,1,  1,1,1,0,0,  0,0,0,0,0]   # 모델 (예측)

In [57]:
# 정답과 예측값 전달
(tn,fp,fn,tp) = confusion_matrix(y_test, y_pre).reshape(-1)
print('tn,fp,fn,tp')
print(tn,fp,fn,tp)

tn,fp,fn,tp
9 4 0 7


In [56]:
confusion_matrix(y_test, y_pre)

array([[9, 4],
       [0, 7]], dtype=int64)

- 정밀도(Precision) : 모델(예측) 중심

In [58]:
from sklearn.metrics import precision_score
precision_score(y_test, y_pre)

0.6363636363636364

- 재현율 : 정답(실제)중심

In [59]:
from sklearn.metrics import recall_score

recall_score(y_test, y_pre)

1.0