#### 배열(Array) 구조 이해하기

In [288]:
l= [[1,2,3],[4,5,6]]
type(l)

list

In [289]:
print(l[0])
print(l[1])

[1, 2, 3]
[4, 5, 6]


In [290]:
for i,a in enumerate(l):
    for j,b in enumerate(a):
        print(l[i][j])

1
2
3
4
5
6


In [291]:
import numpy as np

In [292]:
np.__version__

'1.26.4'

In [293]:
print(np.ndarray)

<class 'numpy.ndarray'>


In [294]:
np.ndarray.__name__

'ndarray'

In [295]:
for i in dir(np.ndarray):
    if not i.startswith('_'):
        if type(np.ndarray.__dict__[i]) != type(np.ndarray.var):
            print(i)

T
base
ctypes
data
dtype
flags
flat
imag
itemsize
nbytes
ndim
real
shape
size
strides


In [296]:
l = [1,2,3,4]
a = np.array(l)
print(a, ', ',type(a))

[1 2 3 4] ,  <class 'numpy.ndarray'>


In [297]:
t = (1,2,3,4)
b = np.array(t)
type(b)

numpy.ndarray

In [298]:
print(a.data)
print(a.data.obj)
print(type(a.data.obj))

[1 2 3 4]
<class 'numpy.ndarray'>


In [299]:
e = np.array(l, dtype=float)
print(e)
print(e.dtype)

[1. 2. 3. 4.]
float64


In [300]:
a2 = np.array([[1,2,3],[4,5,6]])
print(f'a2.shape    : {a2.shape}')
print(f'a2.ndim     : {a2.ndim}')
print(f'a2.dtype    : {a2.dtype}')
print(f'a2.itemsize : {a2.itemsize}')
print(f'a2.size     : {a2.size}')
print(f'a2.strides  : {a2.strides}')

a2.shape    : (2, 3)
a2.ndim     : 2
a2.dtype    : int32
a2.itemsize : 4
a2.size     : 6
a2.strides  : (12, 4)


In [301]:
print(np.ndarray.__bases__)
print(np.matrix.__bases__)

(<class 'object'>,)
(<class 'numpy.ndarray'>,)


#### 넘파이 모듈의 함수 특징

In [302]:
(a!=0).any

<function ndarray.any>

In [303]:
np.any

<function any at 0x00000241FBC49170>

In [304]:
np.ndarray.any is np.core.fromnumeric.any

False

In [305]:
np_ = set(dir(np))
nd_ = set(dir(np.ndarray))
npd_ = np_&nd_
len(npd_)

48

In [306]:
count = 0
for i in list(npd_):
    count += 1
    print(i, end=' ')
    if count%5 == 0:
        print()

swapaxes squeeze any argmax __doc__ 
cumprod reshape conj ndim put 
choose diagonal clip sort nonzero 
real argsort var min repeat 
transpose copy dtype conjugate round 
sum dot cumsum nbytes imag 
size resize ravel shape ptp 
__dir__ prod take max argpartition 
argmin searchsorted std trace all 
compress mean partition 

In [307]:
a = dir(np)
np.ufunc

numpy.ufunc

In [308]:
# count = 0
# for i in a:
#     if i == 'Tester':
#         continue
#     if type(np.__dict__[i]) == np.ufunc:
#         print(i, end = ' ')
#         count += 1
#         if count%5 == 0:
#             print()

In [309]:
a = np.arange(6,10)
b = np.arange(10,14)
c = a * b
print(a)
print(b)
print(c)

[6 7 8 9]
[10 11 12 13]
[ 60  77  96 117]


In [310]:
# 축 연산
a2 = np.array([1,2,3,4])
print(a2)
a2 = a2.reshape(2,2)
print(a2)

[1 2 3 4]
[[1 2]
 [3 4]]


In [311]:
print(np.sum(a2))
print(np.sum(a2,axis=0))
print(np.sum(a2,axis=1))

10
[4 6]
[3 7]


In [312]:
a = np.array([4,5])
print(a.shape)
b = np.array([3,4,6])
print(b.shape)

(2,)
(3,)


In [313]:
try:
    a+b
except Exception as e:
    print(e)

operands could not be broadcast together with shapes (2,) (3,) 


#### 배열 할당과 검색

In [314]:
a = np.array([[1,2],[3,4]])
b = a

In [315]:
b[0] = 999
print(a)
print(b)

[[999 999]
 [  3   4]]
[[999 999]
 [  3   4]]


In [316]:
f = np.array([4,5,6,7,8])
e = f.copy()
g = f[:]
g.base

array([4, 5, 6, 7, 8])

In [317]:
np.may_share_memory(g,f)

True

In [318]:
l = list(range(1,10))
l

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [319]:
index = slice(1,3)
l.__getitem__(index)

[2, 3]

In [320]:
a = np.array([1,2,3,4,5,6,7])
index = 1
a.__getitem__(index)

2

In [321]:
index = slice(1,3)
a.__getitem__(index)

array([2, 3])

In [322]:
index = [1]
a.__getitem__(index)

array([2])

In [323]:
index = a<4
index

array([ True,  True,  True, False, False, False, False])

In [324]:
a.__getitem__(index)

array([1, 2, 3])

## 선형대수 기본 알아보기

#### 스칼라와 벡터 알아보기

In [325]:
a = np.array(43)
print((type(a)))

<class 'numpy.ndarray'>


In [326]:
a

array(43)

In [327]:
print(a.ndim)
print(a.shape)
print(a.dtype)
print(a==43)

0
()
int32
True


In [328]:
v = np.array([43])
type(v)
v

array([43])

In [329]:
print(v.ndim)
print(v.shape)

1
(1,)


In [330]:
# arange() : 특정 범위와 간격을 지정해서 배열을 만드는 함수
#            정수와 실수 등으로 지정해서 다차원 배열을 만들 수 있음
v = np.arange(10)
v.dtype

dtype('int32')

In [331]:
v1 = np.arange(10.5,20.5,0.5)
v1

array([10.5, 11. , 11.5, 12. , 12.5, 13. , 13.5, 14. , 14.5, 15. , 15.5,
       16. , 16.5, 17. , 17.5, 18. , 18.5, 19. , 19.5, 20. ])

In [332]:
print(v1.dtype)
print(v1.size)

float64
20


In [333]:
# linspace() : 특정 범위를 전부 포함해서 총 원소의 개수에 맞춰서 다차원 배열을 만드는 함수
#              종료점을 포함하시 않을 때는 endpoint = False
#              원소값들의 차이인 간격은 retstep = True를 지정해 확인
la = np.linspace(1,10,10)
la

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [334]:
la.dtype

dtype('float64')

In [335]:
la1 = np.linspace(1,10,10, endpoint=False, retstep=True)
la1

(array([1. , 1.9, 2.8, 3.7, 4.6, 5.5, 6.4, 7.3, 8.2, 9.1]), 0.9)

In [336]:
la2 = np.linspace(0,2,4)
la2

array([0.        , 0.66666667, 1.33333333, 2.        ])

In [337]:
# logspace() : 특정 범위의 log값을 원소로 다차원 배열을 만드는 함수
lo = np.logspace(0,2,4)
lo

array([  1.        ,   4.64158883,  21.5443469 , 100.        ])

In [338]:
for i in la2:
    print(np.power(10,i))
# np.power(m,n) : m의 n제곱

1.0
4.641588833612778
21.544346900318832
100.0


- 벡터크기 : 각 원소를 제곱한 후 합산한 것을 제곱근 처리 (≒ 피타고라스 정리)

In [339]:
v = np.arange(3,5)
v

array([3, 4])

In [340]:
np.hypot(v[0],v[1])

5.0

In [341]:
v_p = np.power(v,2)         # 원소의 제곱
v_r = np.sqrt(np.sum(v_p))  # 원소의 제곱의 합 => 제곱근
v_r

5.0

In [342]:
np.linalg.norm(v)

5.0

In [343]:
# 표준 단위 벡터 : 위치는 원소 중에 하나가 1이고 나머지 원소가 0
# 표기 방법 : e에 첨자를 부여해서 인덱스 위치에 해당하는 원소만 1로 가짐

In [344]:
e1 = np.array([1,0,0])
e2 = np.array([0,1,0])
e3 = np.array([0,0,1])

In [345]:
print(np.linalg.norm(e1))
print(np.linalg.norm(e2))
print(np.linalg.norm(e3))

1.0
1.0
1.0


In [346]:
# 단위 벡터 : 일반적인 단위 벡터를 구할 때는 벡터의 정규화인 벡터의 크기를 구하고 
#            이를 벡터의 원소에 나눠서 구함

In [347]:
v_3 = np.array([1,2,3])
v_3_n = np.linalg.norm(v_3)
v_3_n

3.7416573867739413

In [348]:
v_3_u = v_3 / v_3_n
v_3_u

array([0.26726124, 0.53452248, 0.80178373])

In [349]:
np.linalg.norm(v_3_u)

1.0

In [350]:
# 벡터의 상등 : 크이와 방향이 같은 경우 (크기는 같지만 방향이 다르면 상등이 아님)
# 벡터의 거리 : 두 벡터의 거리 = 벡터간의 차를 계산한 후 제곱 -> 그 합에 제곱근 처리
#               (= 피타고라스 정리)

#### 행렬(Matrix) 알아보기

In [351]:
# 행렬 만들기 : 리스트가 내표된 리스트를 array 함수에 전달해서 2차원배열인 행렬 생성
A = np.array([[43],[44]])
type(A)

numpy.ndarray

In [352]:
A

array([[43],
       [44]])

In [353]:
print(A.dtype)
print(A.ndim)
print(A.shape)

int32
2
(2, 1)


In [354]:
# 행렬 랭크 : 행렬 내부에 벡터들이 서로 조합해서 구성할 수 없는 벡터의 개수 
#            선형독립이 아닌 벡터가 있을 때는(=종속된 벡터가 많을수록) 랭크가 작아짐 

In [355]:
# 행렬식이 0인 경우는 내부에 선형 독립이 아닌 벡터가 존재
c1 = np.array([[1,2,4],[2,4,8],[3,4,5]])
np.linalg.matrix_rank(c1)

2

In [356]:
np.linalg.det(c1)

0.0

In [357]:
c1[0]*2 - c1[1]

array([0, 0, 0])

In [358]:
# 행렬식이 0이 아니므로 선부 선형독립인 벡터임
c2 = np.array([[1,3,4],[1,8,5],[2,3,4]])
np.linalg.matrix_rank(c2)

3

In [359]:
np.linalg.det(c2)

-17.0

In [360]:
np.linalg.matrix_rank(c2.T)

3

In [361]:
# 축 알아보기 : 행렬은 2개의 축을 가지므로 내부의 원소를 축(axis)위로 계산 가능
#              3차원텐서(배열)도 축에 따른 계산 가능

In [362]:
A = np.array([[2,3],[4,5]])
A.sum()

14

In [363]:
print(A.sum(axis=0))
print(A.sum(axis=1))

[6 8]
[5 9]


In [364]:
C = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
C.ndim

3

In [365]:
C.shape

(2, 2, 2)

In [366]:
# 축에 따른 검색
C[0]

array([[1, 2],
       [3, 4]])

In [367]:
C[1]

array([[5, 6],
       [7, 8]])

In [368]:
# 축에 따른 계산
print(C.sum(axis=0),',')
print(C.sum(axis=1),',')
print(C.sum(axis=2),',')

[[ 6  8]
 [10 12]] ,
[[ 4  6]
 [12 14]] ,
[[ 3  7]
 [11 15]] ,


In [369]:
# 확장 및 축소하기 : 축을 기준으로 배열의 차원의 확대/축소를 함수나 메서드로 처리

# 차원 확장
x = np.array([1,2])
y = np.expand_dims(x,axis=1) # 열 확장
z = np.expand_dims(x,axis=0) # 행 확장

In [370]:
print(x)
print(y)
print(z)

[1 2]
[[1]
 [2]]
[[1 2]]


In [371]:
# 차원 축소
x = np.array([[1,4,5],[4,5,6],[7,8,9]])
x

array([[1, 4, 5],
       [4, 5, 6],
       [7, 8, 9]])

In [372]:
x.flatten() # 메모리 공유 X : 원본 변화 X

array([1, 4, 5, 4, 5, 6, 7, 8, 9])

In [373]:
x.ravel() # 메모리 공유 O : 원본 변화 O

array([1, 4, 5, 4, 5, 6, 7, 8, 9])

#### 행렬(Matrix) 종류 알아보기

In [374]:
# 정사각 행렬 : 행과 열의 길이가 같은 행렬, 이 행렬의 대각선 원소를 trace로 처리 할 수 있음

In [375]:
# 대각 행렬 : 정사각행렬일 때 대각선의 원소를 제외한 모든 원소가 0으로 구성할 수 있음

In [376]:
# 삼각 행렬 
# 하삼각 행렬 : 정방행렬의 주 대각선의 위 인덱스의 원소값이 전부 0이고 밑의 원소는 값을 가짐
# 상삼각 행렬 : 그 반대 (대각선 위의 원소가 값을 가짐)
a = np.arange(1,10).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [377]:
# 하삼각행렬
np.tril(a)

array([[1, 0, 0],
       [4, 5, 0],
       [7, 8, 9]])

In [378]:
# 상삼각행렬
np.triu(a)

array([[1, 2, 3],
       [0, 5, 6],
       [0, 0, 9]])

In [379]:
# 대칭행렬 : 주 대각선을 기준으로 아래의 원소와 위의 원소가 동일한 값을 가진 행렬
#           대칭행렬을 가지고 전치행렬을 만들어도 동일한 형태 유지
X = np.array([[1,2,3],[2,3,5],[3,5,6]])
X

array([[1, 2, 3],
       [2, 3, 5],
       [3, 5, 6]])

In [380]:
X.T

array([[1, 2, 3],
       [2, 3, 5],
       [3, 5, 6]])

In [381]:
np.array_equal(X,X.T)

True

In [382]:
np.array_equiv(X,X.T)

True

In [383]:
# 치환행렬 : 단위행렬이나 행렬의 행을 교환해서 재구성하거나 
#           특정상수를 곱하고 행을 교환 시킬 수 있는 행렬
#           (연립방정식의 해를 구할 때 선형대수로 바꾸어서 문제를 풀 때 사용)

a = np.arange(1,10).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [384]:
b = np.eye(3, dtype='int')
b

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [385]:
np.dot(a,b)
# 단위행렬과 연산하면 치환되지 않음 (np.dot() : 행렬의 곱셈)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [386]:
c = np.array([[0,1,0],[1,0,0],[0,0,1]])
np.dot(a,c)
# 단위행렬을 변환해서 연산하면 원소들을 치환

array([[2, 1, 3],
       [5, 4, 6],
       [8, 7, 9]])

In [387]:
# 직교행렬 : 자기자신의 행렬과 전치행렬을 행렬곱으로 계산한것, 직교 행렬의 전치행렬 = 역행렬
from scipy.stats import ortho_group

In [388]:
x = ortho_group.rvs(3)
x

array([[ 0.16452688, -0.81215265,  0.55976689],
       [-0.90352559,  0.10356904,  0.41583044],
       [-0.39569232, -0.574179  , -0.71676082]])

In [389]:
i3 = np.dot(x,x.T)
i3

array([[ 1.00000000e+00,  2.22928863e-16,  1.23174849e-16],
       [ 2.22928863e-16,  1.00000000e+00, -7.45263625e-17],
       [ 1.23174849e-16, -7.45263625e-17,  1.00000000e+00]])

In [390]:
# np.allclose 함수로 단위 행렬인지 확인
c = np.eye(3)
np.allclose(c,i3)

True

In [391]:
# 전치행렬 : 기존의 행과 열을 서로 바꾸는 것 보통 위 첨자에 T 사용

## 다차원 배열의 검색

#### 배열의 일반 검색

In [392]:
# 색인 검색 : 다차원 배열의 index는 0부터 시작, 하나의 원소를 검색할 때 사용
#            벡터일 때는 스칼라, 행렬일때는 벡터 검색

In [393]:
# 슬라이스 검색 : 배열의 부분집합 만듦
# 생략 기호 : 점 3개 => 내부적으로 검색할 때 다차원 배열의 모양을 자동으로 인식해서 처리

#### 논리식 검색과 팬시 검색

In [394]:
# 논리 검색 : 논리식을 평가한 후 참인 경우의 원소만을 검색하는 것
L = np.random.randn(7,4)
L

array([[ 0.75262109,  0.83218682, -0.90032603, -1.8069375 ],
       [-0.22552992, -0.39324245, -0.22368375,  0.87982427],
       [-0.21482171, -0.18151913, -0.93453016,  1.51133754],
       [-0.75063677, -1.1734127 , -1.7400059 , -0.59747717],
       [-0.05715542,  0.73145002,  1.20625834, -0.91282303],
       [-0.34628408, -1.01202004, -0.79655903, -1.65627628],
       [ 1.14727189, -1.33661698, -0.9779898 , -0.89879782]])

In [395]:
L[L<0]

array([-0.90032603, -1.8069375 , -0.22552992, -0.39324245, -0.22368375,
       -0.21482171, -0.18151913, -0.93453016, -0.75063677, -1.1734127 ,
       -1.7400059 , -0.59747717, -0.05715542, -0.91282303, -0.34628408,
       -1.01202004, -0.79655903, -1.65627628, -1.33661698, -0.9779898 ,
       -0.89879782])

In [396]:
L[L<0] = 999
L

array([[7.52621093e-01, 8.32186819e-01, 9.99000000e+02, 9.99000000e+02],
       [9.99000000e+02, 9.99000000e+02, 9.99000000e+02, 8.79824268e-01],
       [9.99000000e+02, 9.99000000e+02, 9.99000000e+02, 1.51133754e+00],
       [9.99000000e+02, 9.99000000e+02, 9.99000000e+02, 9.99000000e+02],
       [9.99000000e+02, 7.31450025e-01, 1.20625834e+00, 9.99000000e+02],
       [9.99000000e+02, 9.99000000e+02, 9.99000000e+02, 9.99000000e+02],
       [1.14727189e+00, 9.99000000e+02, 9.99000000e+02, 9.99000000e+02]])

In [397]:
LC = L[L==999]
LC

array([999., 999., 999., 999., 999., 999., 999., 999., 999., 999., 999.,
       999., 999., 999., 999., 999., 999., 999., 999., 999., 999.])

In [398]:
# 논리검색은 and, or, not 연산 사용 불가능 => 대신 logical_and 등의 함수 사용
L = np.arange(0,12)
L

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [399]:
try:
    L and L
except Exception as e:
    print(e)

The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()


In [400]:
np.logical_and(L,L)

array([False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True])

In [401]:
L[np.logical_and(L,L)]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [402]:
# 팬시 검색 : 다차원 배열의 검색에 배열을 전달해서 여러 개의 원소를 조회
# 팬시 검색 결과 : 새로운 다차원 배열

In [403]:
# 팬시 검색과 슬라이스 검색의 차이
x = np.arange(1,15)
pos2 = np.array([1,2,2,2])
c = x[pos2]
np.may_share_memory(x,c)

False

In [404]:
y = x[:4]
np.may_share_memory(x,y)

True

In [405]:
# 팬시 검색 : 행과 열을 전부 리스트로 전달 -> 두 리스트의 쌍으로 구성해서 배열의 원소 표시
#            원하는 결과 얻기 위해서 np.ix_ 함수로 처리
x = np.arange(16).reshape(4,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [406]:
x[[3,0]]

array([[12, 13, 14, 15],
       [ 0,  1,  2,  3]])

In [407]:
# 행과 열을 전부 리스트로 검색
x[[1,2],[2,3]]

array([ 6, 11])

In [408]:
# np.ix_ 함수로 처리 : np.ix_([행인덱스],[열인덱스])
x[np.ix_([1,2],[2,3])]

array([[ 6,  7],
       [10, 11]])

In [409]:
# 팬시검색은 일반검색, 슬라이스 검색과 혼합해서 처리 가능
# 팬시검색을 혼합한 결과도 새로운 배열 만듦
x = np.arange(10).reshape(2,5)
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [410]:
a = x[[0,1],0]
a

array([0, 5])

In [411]:
# 팬시검색은 새로운 배열을 만들어서 검색할 때 다양한 조건을 넣어 새로운배열 만들 수 있음
x = np.arange(9).reshape(3,3)
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [412]:
# 배열보다 작게 조회
a = x[1:, 1:]
a

array([[4, 5],
       [7, 8]])

In [413]:
np.may_share_memory(x,a)

True

In [414]:
# 배열보다 크게 조회
a = np.reshape(np.arange(10), (2,5))
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [415]:
c = a[[1,1,1],np.newaxis]
c

array([[[5, 6, 7, 8, 9]],

       [[5, 6, 7, 8, 9]],

       [[5, 6, 7, 8, 9]]])

In [416]:
c.shape

(3, 1, 5)

#### 메소드나 함수로 검색하기

In [417]:
# 메소드로 검색 1 : 다차원 배열의 메소드인 item, view를 사용해서 검색가능
#                  itemset으로 내부 원소 갱신 가능
x = np.arange(9).reshape(3,3)
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [418]:
x.item(1)

1

In [419]:
x.item((1,2))

5

In [420]:
x.item((2,2))

8

In [421]:
x.itemset(2,20)
x

array([[ 0,  1, 20],
       [ 3,  4,  5],
       [ 6,  7,  8]])

In [422]:
x.itemset((2,2),10)
x.view()

array([[ 0,  1, 20],
       [ 3,  4,  5],
       [ 6,  7, 10]])

In [423]:
# 메소드로 검색 2 : 다차원 배열의 take 메소드로 검색하고 put 메소드로 내부 원소 변경 가능
b= np.linspace(1,10,10).reshape(2,5)
b

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.]])

In [424]:
pos1=[3,4]
b.take(pos1)

array([4., 5.])

In [425]:
pos2 = [[0,1],[3,4]]
b.take(pos2)

array([[1., 2.],
       [4., 5.]])

In [426]:
c = b.copy()
c.put(pos1,30)
c

array([[ 1.,  2.,  3., 30., 30.],
       [ 6.,  7.,  8.,  9., 10.]])

In [427]:
c.put(pos1,[10,20])
c

array([[ 1.,  2.,  3., 10., 20.],
       [ 6.,  7.,  8.,  9., 10.]])

In [428]:
# 질의 함수 1 : 넘파이 함수 choose()는 인덱스로 검색
x = np.arange(9).reshape(3,3)
np.choose(0,x)

array([0, 1, 2])

In [429]:
np.choose(tuple([0,1,2]),x)

array([0, 4, 8])

In [430]:
np.choose(tuple([2,1,0]),x)

array([6, 4, 2])

In [431]:
# 질의 함수 2 : 넘파이 where() 는 조건식 판단을 검색에 넣어 조회 가능
#              두가지를 합친 함수 : select(), extract()
np.where(x>4)

(array([1, 2, 2, 2], dtype=int64), array([2, 0, 1, 2], dtype=int64))

In [432]:
x[np.where(x>4)]

array([5, 6, 7, 8])

In [433]:
a = np.select(x>5, x*2)
a

array([12, 14, 16])

In [434]:
np.extract(x>4,x)

array([5, 6, 7, 8])

## 다차원 배열의 연산

#### 브로드캐스팅 이해하기

In [435]:
# 브로드캐스팅 : 차원이 다른 배열간의 계산을 할 때에는 원소별 계산을 위해 동일한 shape 구성

In [436]:
x = np.arange(10).reshape(2,5)
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [437]:
y = np.arange(5)
y

array([0, 1, 2, 3, 4])

In [438]:
z = np.broadcast(x,y)

In [439]:
# 1차원 배열의 2차원 배열로 변환
z.shape, z.ndim

((2, 5), 2)

In [440]:
for i in z:
    print(i)

(0, 0)
(1, 1)
(2, 2)
(3, 3)
(4, 4)
(5, 0)
(6, 1)
(7, 2)
(8, 3)
(9, 4)


In [441]:
x+y

array([[ 0,  2,  4,  6,  8],
       [ 5,  7,  9, 11, 13]])

In [442]:
# 차원이 다른 배열에 대한 연산을 할 때 브로드캐스팅 처리 방법
x1 = np.ones(3)
x2 = np.ones((2,3))

In [443]:
# 마지막 원소 개수 확인
x1.shape, x2.shape

((3,), (2, 3))

In [444]:
x1.shape[0] == x2.shape[1]

True

In [445]:
# 차원 추가
x1 = x1[np.newaxis,]
x1.shape

(1, 3)

In [446]:
# 행을 하나 더 추가
x1 = np.vstack((x1[0],x1[0]))
x1

array([[1., 1., 1.],
       [1., 1., 1.]])

In [447]:
# 연산
x1.shape == x2.shape

True

In [448]:
x1+x2

array([[2., 2., 2.],
       [2., 2., 2.]])

In [449]:
# 행벡터와 열벡터 브로드캐스팅 확장 : 형벡터와 열벡터의 연산은 동일한 shape를 구성한 후 원소별로 계산

#### 행렬의 연산

In [450]:
# 벡터의 내적 : 두 벡터의 크기와 내각의 곱, 또는 두 벡터의 원소별 곱셈 후에 더해서 구할 수 O
#              두 벡터가 수직인지 확인할 때 많이 사용
# a@b / np.dot(a,b) / np.inner(a,b)

In [451]:
# 벡터의 외적 : 두 벡터의 외적은 두 벡터를 평면으로 인식한 후에
#              두 벡터의 만나는 점의 수직인 벡터를 구하는 것
# np.cross(a,b)

In [452]:
# 행렬 dot product : A 행렬의 행과 B행렬의 열 간의 원소를 곱해서 더한 값 (행렬의 곱셈)
# np.dot(a,b) / a.dot(b) / a@b

In [453]:
# 행렬 dot product 계산 - 행렬분해 이용
# 열벡터로 변환한 후 dot product 연산 후 하나로 통합

#### 행렬식, 역행렬 처리하기

In [454]:
# 행렬식 : 정사각행렬일 때 이 원소들을 대응해서 값을 구하는 방식
#        정사각행렬이 아니면 행렬식 계산 불가능
#        행렬식으로 계산하면 벡터와 행렬간의 닷연산을 통해 선형변환한 결과의 부피를 구할 수 O
#        행렬의 차원이 커질 경우 행렬식을 구할 때는 소행렬식을 사용해서 행렬식을 구할 수 있음

In [ ]:
# 역행렬 : 역행렬을 구할 때 행렬식의 결괏값으로 나누는 것이 매우 중요
#          행렬식이 0이 나오면 수학적 계산 불가능 => 역행렬 계산 불가능

In [455]:
# 역행렬의 교환법칙 : 역행렬의 행렬곱 연산은 반대로 계산해도 동일한 단위행렬 나옴
# 의사 역행렬 : 특정 행렬이 역행렬이 없을 때에 역행렬을 임의로 계산하는 것

#### einsum 연산 확인하기

In [456]:
# 아인슈타인의 합 : 선형대수학을 물리학에 응용하면서 좌표계에 관한 공식을 다룰 때 유용한 표기규칙
# 선형대수를 편리하게 계산할 수 있는 방법
# 전치행렬을 처리하려면 먼저 문자열에 두 행렬의 인덱스 정보를 반대로 만듦

In [458]:
# 하나의 벡터와 행렬 계산
# Einsum으로 벡터의 원소를 합산할 경우는 하나의 인덱스를 표시하고 그 결과는 아무것도 표시 X
# 벡터는 하나, 행렬은 두개의 인덱스를 문자로 표시해야 함