#### 배열(Array) 구조 이해하기

In [23]:
l= [[1,2,3],[4,5,6]]
type(l)

list

In [24]:
print(l[0])
print(l[1])

[1, 2, 3]
[4, 5, 6]


In [25]:
for i,a in enumerate(l):
    for j,b in enumerate(a):
        print(l[i][j])

1
2
3
4
5
6


In [26]:
import numpy as np

In [27]:
np.__version__

'1.26.4'

In [28]:
print(np.ndarray)

<class 'numpy.ndarray'>


In [29]:
np.ndarray.__name__

'ndarray'

In [30]:
for i in dir(np.ndarray):
    if not i.startswith('_'):
        if type(np.ndarray.__dict__[i]) != type(np.ndarray.var):
            print(i)

T
base
ctypes
data
dtype
flags
flat
imag
itemsize
nbytes
ndim
real
shape
size
strides


In [31]:
l = [1,2,3,4]
a = np.array(l)
print(a, ', ',type(a))

[1 2 3 4] ,  <class 'numpy.ndarray'>


In [32]:
t = (1,2,3,4)
b = np.array(t)
type(b)

numpy.ndarray

In [33]:
print(a.data)
print(a.data.obj)
print(type(a.data.obj))

[1 2 3 4]
<class 'numpy.ndarray'>


In [34]:
e = np.array(l, dtype=float)
print(e)
print(e.dtype)

[1. 2. 3. 4.]
float64


In [35]:
a2 = np.array([[1,2,3],[4,5,6]])
print(f'a2.shape    : {a2.shape}')
print(f'a2.ndim     : {a2.ndim}')
print(f'a2.dtype    : {a2.dtype}')
print(f'a2.itemsize : {a2.itemsize}')
print(f'a2.size     : {a2.size}')
print(f'a2.strides  : {a2.strides}')

a2.shape    : (2, 3)
a2.ndim     : 2
a2.dtype    : int32
a2.itemsize : 4
a2.size     : 6
a2.strides  : (12, 4)


In [36]:
print(np.ndarray.__bases__)
print(np.matrix.__bases__)

(<class 'object'>,)
(<class 'numpy.ndarray'>,)


#### 넘파이 모듈의 함수 특징

In [37]:
(a!=0).any

<function ndarray.any>

In [38]:
np.any

<function any at 0x000001553BC86230>

In [39]:
np.ndarray.any is np.core.fromnumeric.any

False

In [40]:
np_ = set(dir(np))
nd_ = set(dir(np.ndarray))
npd_ = np_&nd_
len(npd_)

48

In [41]:
count = 0
for i in list(npd_):
    count += 1
    print(i, end=' ')
    if count%5 == 0:
        print()

all reshape squeeze mean size 
argmax nonzero partition argsort any 
shape imag resize ptp cumprod 
searchsorted std clip choose __doc__ 
trace conj swapaxes diagonal nbytes 
argmin __dir__ transpose ravel copy 
max sum put round repeat 
cumsum sort prod argpartition compress 
dtype var conjugate dot ndim 
real take min 

In [42]:
a = dir(np)
np.ufunc

numpy.ufunc

In [43]:
# count = 0
# for i in a:
#     if i == 'Tester':
#         continue
#     if type(np.__dict__[i]) == np.ufunc:
#         print(i, end = ' ')
#         count += 1
#         if count%5 == 0:
#             print()

abs absolute add arccos arccosh 
arcsin arcsinh arctan arctan2 arctanh 
bitwise_and bitwise_not bitwise_or bitwise_xor cbrt 
ceil conj conjugate copysign cos 
cosh deg2rad degrees divide divmod 
equal exp exp2 expm1 fabs 
float_power floor floor_divide fmax fmin 
fmod frexp gcd greater greater_equal 
heaviside hypot invert isfinite isinf 
isnan isnat lcm ldexp left_shift 
less less_equal log log10 log1p 
log2 logaddexp logaddexp2 logical_and logical_not 
logical_or logical_xor matmul maximum minimum 
mod modf multiply negative nextafter 
not_equal positive power rad2deg radians 
reciprocal remainder right_shift rint sign 
signbit sin sinh spacing sqrt 
square subtract tan tanh 

KeyError: 'testing'

In [45]:
a = np.arange(6,10)
b = np.arange(10,14)
c = a * b
print(a)
print(b)
print(c)

[6 7 8 9]
[10 11 12 13]
[ 60  77  96 117]


In [46]:
# 축 연산
a2 = np.array([1,2,3,4])
print(a2)
a2 = a2.reshape(2,2)
print(a2)

[1 2 3 4]
[[1 2]
 [3 4]]


In [47]:
print(np.sum(a2))
print(np.sum(a2,axis=0))
print(np.sum(a2,axis=1))

10
[4 6]
[3 7]


In [48]:
a = np.array([4,5])
print(a.shape)
b = np.array([3,4,6])
print(b.shape)

(2,)
(3,)


In [49]:
try:
    a+b
except Exception as e:
    print(e)

operands could not be broadcast together with shapes (2,) (3,) 


#### 배열 할당과 검색

In [51]:
a = np.array([[1,2],[3,4]])
b = a

array([[1, 2],
       [3, 4]])

In [52]:
b[0] = 999
print(a)
print(b)

[[999 999]
 [  3   4]]
[[999 999]
 [  3   4]]


In [53]:
f = np.array([4,5,6,7,8])
e = f.copy()
g = f[:]
g.base

array([4, 5, 6, 7, 8])

In [54]:
np.may_share_memory(g,f)

True

In [55]:
l = list(range(1,10))
l

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [56]:
index = slice(1,3)
l.__getitem__(index)

[2, 3]

In [57]:
a = np.array([1,2,3,4,5,6,7])
index = 1
a.__getitem__(index)

2

In [58]:
index = slice(1,3)
a.__getitem__(index)

array([2, 3])

In [60]:
index = [1]
a.__getitem__(index)

array([2])

In [61]:
index = a<4
index

array([ True,  True,  True, False, False, False, False])

In [62]:
a.__getitem__(index)

array([1, 2, 3])

## 선형대수 기본 알아보기

#### 스칼라와 벡터 알아보기

In [63]:
a = np.array(43)
print((type(a)))

numpy.ndarray

In [64]:
a

array(43)

In [65]:
print(a.ndim)
print(a.shape)
print(a.dtype)
print(a==43)

0
()
int32
True


In [67]:
v = np.array([43])
type(v)
v

array([43])

In [68]:
print(v.ndim)
print(v.shape)

1
(1,)


In [70]:
# arange() : 특정 범위와 간격을 지정해서 배열을 만드는 함수
#            정수와 실수 등으로 지정해서 다차원 배열을 만들 수 있음
v = np.arange(10)
v.dtype

dtype('int32')

In [72]:
v1 = np.arange(10.5,20.5,0.5)
v1

array([10.5, 11. , 11.5, 12. , 12.5, 13. , 13.5, 14. , 14.5, 15. , 15.5,
       16. , 16.5, 17. , 17.5, 18. , 18.5, 19. , 19.5, 20. ])

In [73]:
print(v1.dtype)
print(v1.size)

float64
20


In [74]:
# linspace() : 특정 범위를 전부 포함해서 총 원소의 개수에 맞춰서 다차원 배열을 만드는 함수
#              종료점을 포함하시 않을 때는 endpoint = False
#              원소값들의 차이인 간격은 retstep = True를 지정해 확인
la = np.linspace(1,10,10)
la

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [75]:
la.dtype

dtype('float64')

In [76]:
la1 = np.linspace(1,10,10, endpoint=False, retstep=True)
la1

(array([1. , 1.9, 2.8, 3.7, 4.6, 5.5, 6.4, 7.3, 8.2, 9.1]), 0.9)

In [78]:
la2 = np.linspace(0,2,4)
la2

array([0.        , 0.66666667, 1.33333333, 2.        ])

In [77]:
# logspace() : 특정 범위의 log값을 원소로 다차원 배열을 만드는 함수
lo = np.logspace(0,2,4)
lo

array([  1.        ,   4.64158883,  21.5443469 , 100.        ])

In [79]:
for i in la2:
    print(np.power(10,i))
# np.power(m,n) : m의 n제곱

1.0
4.641588833612778
21.544346900318832
100.0


- 벡터크기 : 각 원소를 제곱한 후 합산한 것을 제곱근 처리 (≒ 피타고라스 정리)

In [80]:
v = np.arange(3,5)
v

array([3, 4])

In [81]:
np.hypot(v[0],v[1])

5.0

In [83]:
v_p = np.power(v,2)         # 원소의 제곱
v_r = np.sqrt(np.sum(v_p))  # 원소의 제곱의 합 => 제곱근
v_r

5.0

In [84]:
np.linalg.norm(v)

5.0

In [89]:
# 표준 단위 벡터 : 위치는 원소 중에 하나가 1이고 나머지 원소가 0
# 표기 방법 : e에 첨자를 부여해서 인덱스 위치에 해당하는 원소만 1로 가짐

In [87]:
e1 = np.array([1,0,0])
e2 = np.array([0,1,0])
e3 = np.array([0,0,1])

In [88]:
print(np.linalg.norm(e1))
print(np.linalg.norm(e2))
print(np.linalg.norm(e3))

1.0
1.0
1.0


In [90]:
# 단위 벡터 : 일반적인 단위 벡터를 구할 때는 벡터의 정규화인 벡터의 크기를 구하고 
#            이를 벡터의 원소에 나눠서 구함

In [96]:
v_3 = np.array([1,2,3])
v_3_n = np.linalg.norm(v_3)
v_3_n

3.7416573867739413

In [97]:
v_3_u = v_3 / v_3_n
v_3_u

array([0.26726124, 0.53452248, 0.80178373])

In [98]:
np.linalg.norm(v_3_u)

1.0

In [99]:
# 벡터의 상등 : 크이와 방향이 같은 경우 (크기는 같지만 방향이 다르면 상등이 아님)
# 벡터의 거리 : 두 벡터의 거리 = 벡터간의 차를 계산한 후 제곱 -> 그 합에 제곱근 처리
#               (= 피타고라스 정리)

#### 행렬(Matrix) 알아보기

In [100]:
# 행렬 만들기 : 리스트가 내표된 리스트를 array 함수에 전달해서 2차원배열인 행렬 생성
A = np.array([[43],[44]])
type(A)

numpy.ndarray

In [101]:
A

array([[43],
       [44]])

In [102]:
print(A.dtype)
print(A.ndim)
print(A.shape)

int32
2
(2, 1)


In [103]:
# 행렬 랭크 : 행렬 내부에 벡터들이 서로 조합해서 구성할 수 없는 벡터의 개수 
#            선형독립이 아닌 벡터가 있을 때는(=종속된 벡터가 많을수록) 랭크가 작아짐 

In [104]:
# 행렬식이 0인 경우는 내부에 선형 독립이 아닌 벡터가 존재
c1 = np.array([[1,2,4],[2,4,8],[3,4,5]])
np.linalg.matrix_rank(c1)

2

In [105]:
np.linalg.det(c1)

0.0

In [106]:
c1[0]*2 - c1[1]

array([0, 0, 0])

In [107]:
# 행렬식이 0이 아니므로 선부 선형독립인 벡터임
c2 = np.array([[1,3,4],[1,8,5],[2,3,4]])
np.linalg.matrix_rank(c2)

3

In [108]:
np.linalg.det(c2)

-17.0

In [109]:
np.linalg.matrix_rank(c2.T)

3

In [110]:
# 축 알아보기 : 행렬은 2개의 축을 가지므로 내부의 원소를 축(axis)위로 계산 가능
#              3차원텐서(배열)도 축에 따른 계산 가능

In [112]:
A = np.array([[2,3],[4,5]])
A.sum()

14

In [113]:
print(A.sum(axis=0))
print(A.sum(axis=1))

[6 8]
[5 9]


In [115]:
C = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
C.ndim

3

In [116]:
C.shape

(2, 2, 2)

In [117]:
# 축에 따른 검색
C[0]

array([[1, 2],
       [3, 4]])

In [118]:
C[1]

array([[5, 6],
       [7, 8]])

In [120]:
# 축에 따른 계산
print(C.sum(axis=0),',')
print(C.sum(axis=1),',')
print(C.sum(axis=2),',')

[[ 6  8]
 [10 12]] ,
[[ 4  6]
 [12 14]] ,
[[ 3  7]
 [11 15]] ,


In [121]:
# 확장 및 축소하기 : 축을 기준으로 배열의 차원의 확대/축소를 함수나 메서드로 처리

# 차원 확장
x = np.array([1,2])
y = np.expand_dims(x,axis=1) # 열 확장
z = np.expand_dims(x,axis=0) # 행 확장

In [122]:
print(x)
print(y)
print(z)

[1 2]
[[1]
 [2]]
[[1 2]]


In [123]:
# 차원 축소
x = np.array([[1,4,5],[4,5,6],[7,8,9]])
x

array([[1, 4, 5],
       [4, 5, 6],
       [7, 8, 9]])

In [124]:
x.flatten() # 메모리 공유 X : 원본 변화 X

array([1, 4, 5, 4, 5, 6, 7, 8, 9])

In [126]:
x.ravel() # 메모리 공유 O : 원본 변화 O

array([1, 4, 5, 4, 5, 6, 7, 8, 9])